/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "rtmpclient.h"
/* Header for class org.limlee_librtmp_RTMPUtil */

#ifndef _Included_org_limlee_rtmplib_RTMPUtil
#define _Included_org_limlee_rtmplib_RTMPUtil
#ifdef __cplusplus
extern "C" {
#endif


jint JNICALL Java_org_limlee_rtmplib_RTMPUtil_open
(JNIEnv *, jobject, jstring);

jint JNICALL Java_org_limlee_rtmplib_RTMPUtil_close
(JNIEnv *, jobject);

jint JNICALL Java_org_limlee_rtmplib_RTMPUtil_isConnected
(JNIEnv *, jobject);

jint JNICALL Java_org_limlee_rtmplib_RTMPUtil_writeFlvFrame
(JNIEnv *, jobject, jbyteArray, jint);


#ifdef __cplusplus
}
#endif
#endif
